// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PawsitivityScheduler.Data;

namespace PawsitiveScheduling.Migrations
{
    [DbContext(typeof(SchedulingContext))]
    [Migration("20210315054146_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PawsitivityScheduler.Data.Breeds.Breed", b =>
                {
                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<int>("BathMinutes")
                        .HasColumnType("int");

                    b.Property<int>("GroomMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("PawsitivityScheduler.Data.Dog", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<int>("AdditionalBathMinutes")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalGroomMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int?>("BreedName")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("BreedName");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("PawsitivityScheduler.Data.Dog", b =>
                {
                    b.HasOne("PawsitivityScheduler.Data.Breeds.Breed", "Breed")
                        .WithMany()
                        .HasForeignKey("BreedName");
                });
#pragma warning restore 612, 618
        }
    }
}
